name: "book_my_house"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../../book-my-house:/workspaces/book-my-house:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
    - "3000:3000"

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    depends_on:
    - selenium

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  
