default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: tmp/book_my_house_development.sqlite

test:
  <<: *default
  adapter: sqlite3
  database: tmp/book_my_house_test.sqlite
