name: Audit
on: [push]

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run bundle-audit
        run: |
          gem install bundler-audit
          bundle-audit check --update

  yarn-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: yarn

      - name: Run yarn-audit
        run: yarn audit

  brakeman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run brakeman
        run: |
          gem install brakeman
          brakeman
